services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: placement-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: placementdb
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres

  redis:
    image: redis:latest
    container_name: placement-redis
    ports:
      - "6379:6379"