package com.keepcalm.placementportal;
import com.keepcalm.placementportal.repository.audit.*;
import com.keepcalm.placementportal.repository.communication.*;
import com.keepcalm.placementportal.repository.offer.*;
import com.keepcalm.placementportal.repository.selection.*;
import com.keepcalm.placementportal.repository.application.*;
import com.keepcalm.placementportal.repository.drive.*;
import com.keepcalm.placementportal.repository.company.*;
import com.keepcalm.placementportal.repository.profile.*;
import com.keepcalm.placementportal.repository.student.*;
import com.keepcalm.placementportal.repository.auth.*;
import com.keepcalm.placementportal.service.storage.*;
import com.keepcalm.placementportal.service.audit.*;
import com.keepcalm.placementportal.service.event.*;
import com.keepcalm.placementportal.service.analytics.*;
import com.keepcalm.placementportal.service.communication.*;
import com.keepcalm.placementportal.service.offer.*;
import com.keepcalm.placementportal.service.selection.*;
import com.keepcalm.placementportal.service.application.*;
import com.keepcalm.placementportal.service.drive.*;
import com.keepcalm.placementportal.service.company.*;
import com.keepcalm.placementportal.service.student.*;
import com.keepcalm.placementportal.service.profile.*;
import com.keepcalm.placementportal.service.auth.*;
import com.keepcalm.placementportal.controller.event.*;
import com.keepcalm.placementportal.controller.analytics.*;
import com.keepcalm.placementportal.controller.communication.*;
import com.keepcalm.placementportal.controller.offer.*;
import com.keepcalm.placementportal.controller.selection.*;
import com.keepcalm.placementportal.controller.application.*;
import com.keepcalm.placementportal.controller.drive.*;
import com.keepcalm.placementportal.controller.company.*;
import com.keepcalm.placementportal.controller.student.*;
import com.keepcalm.placementportal.controller.profile.*;
import com.keepcalm.placementportal.controller.auth.*;
import com.keepcalm.placementportal.entity.auth.*;
import com.keepcalm.placementportal.entity.profile.*;
import com.keepcalm.placementportal.entity.student.*;
import com.keepcalm.placementportal.entity.company.*;
import com.keepcalm.placementportal.entity.drive.*;
import com.keepcalm.placementportal.entity.application.*;
import com.keepcalm.placementportal.entity.selection.*;
import com.keepcalm.placementportal.entity.offer.*;
import com.keepcalm.placementportal.entity.communication.*;
import com.keepcalm.placementportal.entity.audit.*;
import com.keepcalm.placementportal.enums.EligibilityRuleType;
import com.keepcalm.placementportal.service.drive.EligibilityEngine;
import org.junit.jupiter.api.Test;
import java.math.BigDecimal;
import java.util.List;
import static org.assertj.core.api.Assertions.assertThat;
class EligibilityEngineTest {
 @Test void evaluatesRulesAndBuildsImmutableProfileSnapshot(){
  Student student=new Student();student.setGender("FEMALE");
  AcademicRecord academic=new AcademicRecord();academic.setCgpa(new BigDecimal("8.20"));academic.setActiveBacklogs(0);academic.setBranch("CSE");academic.setGraduationYear(2027);academic.setTenthPercentage(new BigDecimal("91"));
  EligibilityRule cgpa=rule(EligibilityRuleType.MIN_CGPA,"{\"value\":8.0}");EligibilityRule branches=rule(EligibilityRuleType.ALLOWED_BRANCHES,"{\"values\":[\"CSE\",\"IT\"]}");
  var result=new EligibilityEngine().evaluate(student,academic,List.of(cgpa,branches));
  assertThat(result.eligible()).isTrue();assertThat(result.snapshot()).containsKeys("evaluatedAt","profile","rules");
  academic.setCgpa(new BigDecimal("7.5"));
  assertThat(((java.util.Map<?,?>)result.snapshot().get("profile")).get("cgpa").toString()).isEqualTo("8.20");
 }
 private EligibilityRule rule(EligibilityRuleType type,String config){EligibilityRule r=new EligibilityRule();r.setRuleType(type);try{r.setConfiguration(new com.fasterxml.jackson.databind.ObjectMapper().readValue(config,java.util.Map.class));}catch(Exception e){throw new RuntimeException(e);}r.setMandatory(true);r.setActive(true);return r;}
}
