package com.keepcalm.placementportal;
import com.fasterxml.jackson.databind.ObjectMapper;import com.keepcalm.placementportal.entity.*;import com.keepcalm.placementportal.enums.*;import com.keepcalm.placementportal.repository.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.test.web.servlet.MockMvc;import java.time.Instant;import java.util.Map;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc class RoundResultPublicationIntegrationTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired InstitutionRepository institutions;@Autowired UserRepository users;@Autowired StudentRepository students;@Autowired CompanyRepository companies;@Autowired CampusDriveRepository drives;@Autowired DriveRoleRepository roles;@Autowired JobApplicationRepository applications;@Autowired PasswordEncoder passwords;
 private String adminToken;private CampusDrive drive;private JobApplication application;
 @BeforeEach void setup()throws Exception{Institution i=institutions.findByCodeIgnoreCaseAndActiveTrue("DEFAULT").orElseGet(()->{Institution x=new Institution();x.setCode("DEFAULT");x.setName("Test College");return institutions.save(x);});String suffix=Long.toString(System.nanoTime());User studentUser=user(i,"roundstudent"+suffix,Role.STUDENT);Student s=new Student();s.setInstitution(i);s.setUser(studentUser);s.setFirstName("Riya");s.setRollNumber("RR"+suffix);s.setPlacementStatus(PlacementStatus.NOT_PLACED);students.save(s);User admin=user(i,"roundadmin"+suffix,Role.ADMIN);adminToken=login(admin.getUsername());Company c=new Company();c.setInstitution(i);c.setName("Round Co "+suffix);companies.save(c);drive=new CampusDrive();drive.setInstitution(i);drive.setCompany(c);drive.setOwner(admin);drive.setTitle("Round Drive");drive.setStatus(DriveStatus.ASSESSMENT);drives.save(drive);DriveRole role=new DriveRole();role.setDrive(drive);role.setTitle("Engineer");role.setPositions(1);role.setCurrency("INR");roles.save(role);application=new JobApplication();application.setInstitution(i);application.setStudent(s);application.setDriveRole(role);application.setDriveId(drive.getId());application.setStatus(ApplicationStatus.ELIGIBLE);application.setAppliedAt(Instant.now());application.setEligibilityPassed(true);application.setEligibilitySnapshot(Map.of("eligible",true));applications.save(application);}
 @Test void publishesResultsTransactionallyAndUpdatesApplicationHistory()throws Exception{String create=mvc.perform(post("/api/v1/admin/drives/"+drive.getId()+"/rounds").header("Authorization","Bearer "+adminToken).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Technical Test\",\"roundType\":\"ASSESSMENT\",\"roundOrder\":1,\"startsAt\":\"2030-01-01T10:00:00Z\",\"endsAt\":\"2030-01-01T11:00:00Z\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long roundId=json.readTree(create).get("id").asLong();String ps=mvc.perform(get("/api/v1/admin/drives/"+drive.getId()+"/rounds/"+roundId+"/participants").header("Authorization","Bearer "+adminToken)).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();long participantId=json.readTree(ps).get(0).get("id").asLong();mvc.perform(post("/api/v1/admin/drives/"+drive.getId()+"/rounds/"+roundId+"/results").header("Authorization","Bearer "+adminToken).contentType(MediaType.APPLICATION_JSON).content("{\"results\":[{\"participantId\":"+participantId+",\"status\":\"QUALIFIED\",\"score\":85,\"attendanceStatus\":\"PRESENT\"}]}" )).andExpect(status().isOk());mvc.perform(post("/api/v1/admin/drives/"+drive.getId()+"/rounds/"+roundId+"/publish-results").header("Authorization","Bearer "+adminToken)).andExpect(status().isOk()).andExpect(jsonPath("$.resultsPublished").value(true));Assertions.assertEquals(ApplicationStatus.SHORTLISTED,applications.findById(application.getId()).orElseThrow().getStatus());}
 private User user(Institution i,String name,Role role){User u=new User();u.setInstitution(i);u.setUsername(name);u.setEmail(name+"@example.com");u.setPasswordHash(passwords.encode("StrongPass1!"));u.setRole(role);u.setIsActive(true);return users.save(u);}private String login(String name)throws Exception{String body=mvc.perform(post("/api/v1/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+name+"\",\"password\":\"StrongPass1!\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(body).get("accessToken").asText();}
}
