package com.keepcalm.placementportal.entity.offer;
import com.keepcalm.placementportal.entity.common.*;
import com.keepcalm.placementportal.repository.audit.*;
import com.keepcalm.placementportal.repository.communication.*;
import com.keepcalm.placementportal.repository.offer.*;
import com.keepcalm.placementportal.repository.selection.*;
import com.keepcalm.placementportal.repository.application.*;
import com.keepcalm.placementportal.repository.drive.*;
import com.keepcalm.placementportal.repository.company.*;
import com.keepcalm.placementportal.repository.profile.*;
import com.keepcalm.placementportal.repository.student.*;
import com.keepcalm.placementportal.repository.auth.*;
import com.keepcalm.placementportal.service.storage.*;
import com.keepcalm.placementportal.service.audit.*;
import com.keepcalm.placementportal.service.event.*;
import com.keepcalm.placementportal.service.analytics.*;
import com.keepcalm.placementportal.service.communication.*;
import com.keepcalm.placementportal.service.offer.*;
import com.keepcalm.placementportal.service.selection.*;
import com.keepcalm.placementportal.service.application.*;
import com.keepcalm.placementportal.service.drive.*;
import com.keepcalm.placementportal.service.company.*;
import com.keepcalm.placementportal.service.student.*;
import com.keepcalm.placementportal.service.profile.*;
import com.keepcalm.placementportal.service.auth.*;
import com.keepcalm.placementportal.entity.audit.*;
import com.keepcalm.placementportal.entity.communication.*;
import com.keepcalm.placementportal.entity.offer.*;
import com.keepcalm.placementportal.entity.selection.*;
import com.keepcalm.placementportal.entity.application.*;
import com.keepcalm.placementportal.entity.drive.*;
import com.keepcalm.placementportal.entity.company.*;
import com.keepcalm.placementportal.entity.profile.*;
import com.keepcalm.placementportal.entity.student.*;
import com.keepcalm.placementportal.entity.auth.*;
import com.keepcalm.placementportal.controller.event.*;
import com.keepcalm.placementportal.controller.analytics.*;
import com.keepcalm.placementportal.controller.communication.*;
import com.keepcalm.placementportal.controller.offer.*;
import com.keepcalm.placementportal.controller.selection.*;
import com.keepcalm.placementportal.controller.application.*;
import com.keepcalm.placementportal.controller.drive.*;
import com.keepcalm.placementportal.controller.company.*;
import com.keepcalm.placementportal.controller.student.*;
import com.keepcalm.placementportal.controller.profile.*;
import com.keepcalm.placementportal.controller.auth.*;
import com.keepcalm.placementportal.enums.OfferStatus;import jakarta.persistence.*;import lombok.*;import java.math.BigDecimal;import java.time.Instant;
@Entity @Table(name="offers",indexes={@Index(name="idx_offer_student",columnList="student_id"),@Index(name="idx_offer_status",columnList="status")})@Getter @Setter @NoArgsConstructor
public class Offer extends AuditedEntity{
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)private Long id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="institution_id",nullable=false)private Institution institution;
 @OneToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="application_id",nullable=false,unique=true)private JobApplication application;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="student_id",nullable=false)private Student student;
 @ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="company_id",nullable=false)private Company company;@Column(name="role_title",nullable=false,length=255)private String roleTitle;
 @Column(name="package_amount",nullable=false,precision=14,scale=2)private BigDecimal packageAmount;@Column(nullable=false,length=3)private String currency;@Column(name="letter_object_key",length=500)private String letterObjectKey;
 @Enumerated(EnumType.STRING)@Column(nullable=false,length=30)private OfferStatus status=OfferStatus.DRAFT;@Column(nullable=false)private boolean verified;@Column(name="response_deadline")private Instant responseDeadline;@Column(name="offered_at")private Instant offeredAt;
}
