package com.keepcalm.placementportal.enums;
public enum DriveStatus { DRAFT, PUBLISHED, APPLICATIONS_OPEN, APPLICATIONS_CLOSED, SCREENING, ASSESSMENT, INTERVIEW, OFFER_RELEASED, COMPLETED, CANCELLED }
