package com.keepcalm.placementportal.enums;
public enum EligibilityRuleType { MIN_CGPA, MAX_ACTIVE_BACKLOGS, ALLOWED_BRANCHES, GRADUATION_YEARS, MIN_TENTH_PERCENTAGE, MIN_TWELFTH_PERCENTAGE, MIN_DIPLOMA_PERCENTAGE, GENDER_RULE, CUSTOM_RULE }
