spring.application.name=placement-portal

#Actuator related endpoints
management.endpoints.web.exposure.include=health,info
management.info.git.mode=full

spring.datasource.url=jdbc:postgresql://localhost:5432/placementdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=${JWT_SECRET}
#in milliseconds, e.g., 3600000 for 1 hour
jwt.expiration=${JWT_EXPIRATION}

cors.allowed-origins=http://localhost:5173
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS