package com.keepcalm.placementportal.service;import com.keepcalm.placementportal.entity.*;import com.keepcalm.placementportal.enums.*;import com.keepcalm.placementportal.exception.DomainException;import com.keepcalm.placementportal.models.round.RoundDtos.*;import com.keepcalm.placementportal.repository.*;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service @RequiredArgsConstructor public class RoundService{
 private final SelectionRoundRepository rounds;private final RoundParticipantRepository participants;private final RoundResultRepository results;private final CampusDriveRepository drives;private final JobApplicationRepository applications;private final ApplicationStatusHistoryRepository history;private final CurrentUserService current;private final AuditService audit;private final NotificationService notifications;
 @Transactional(readOnly=true)public List<RoundDto> list(Long driveId){drive(driveId);return rounds.findByDriveIdAndArchivedFalseOrderByRoundOrderAsc(driveId).stream().map(this::dto).toList();}
 @Transactional public RoundDto create(Long driveId,Upsert r){CampusDrive d=drive(driveId);SelectionRound round=new SelectionRound();round.setDrive(d);apply(round,r);rounds.save(round);for(JobApplication a:applications.findByDriveRoleDriveIdAndInstitutionId(driveId,current.principal().institutionId()))if(Set.of(ApplicationStatus.ELIGIBLE,ApplicationStatus.SHORTLISTED,ApplicationStatus.IN_PROCESS).contains(a.getStatus())){RoundParticipant p=new RoundParticipant();p.setRound(round);p.setApplication(a);participants.save(p);}audit.record("SELECTION_ROUND_CREATED","SelectionRound",round.getId(),Map.of("driveId",driveId));return dto(round);}
 @Transactional public RoundDto update(Long driveId,Long id,Upsert r){SelectionRound x=round(driveId,id);if(x.isResultsPublished())throw DomainException.conflict("ROUND_RESULTS_PUBLISHED","Published round cannot be edited");apply(x,r);audit.record("SELECTION_ROUND_UPDATED","SelectionRound",id,Map.of());return dto(x);}
 @Transactional public void delete(Long driveId,Long id){SelectionRound x=round(driveId,id);if(x.isResultsPublished())throw DomainException.conflict("ROUND_RESULTS_PUBLISHED","Published round cannot be deleted");x.setArchived(true);audit.record("SELECTION_ROUND_ARCHIVED","SelectionRound",id,Map.of());}
 @Transactional(readOnly=true)public List<ParticipantDto> participants(Long driveId,Long id){SelectionRound r=round(driveId,id);return participants.findByRoundIdOrderByApplicationStudentRollNumberAsc(r.getId()).stream().map(this::participantDto).toList();}
 @Transactional public Map<String,Object> saveResults(Long driveId,Long id,Results request){SelectionRound round=round(driveId,id);if(round.isResultsPublished())throw DomainException.conflict("ROUND_RESULTS_PUBLISHED","Results are already published");for(ResultItem item:request.results()){RoundParticipant p=participants.findByIdAndRoundId(item.participantId(),id).orElseThrow(()->DomainException.notFound("Round participant not found"));if(item.attendanceStatus()!=null)p.setAttendanceStatus(item.attendanceStatus());RoundResult result=results.findByParticipantId(p.getId()).orElseGet(()->{RoundResult x=new RoundResult();x.setParticipant(p);return x;});result.setStatus(item.status());result.setScore(item.score());result.setNotes(item.notes());results.save(result);}audit.record("ROUND_RESULTS_UPDATED","SelectionRound",id,Map.of("count",request.results().size()));return Map.of("updated",request.results().size());}
 @Transactional public RoundDto publish(Long driveId,Long id){SelectionRound round=round(driveId,id);if(round.isResultsPublished())return dto(round);List<RoundParticipant> ps=participants.findByRoundIdOrderByApplicationStudentRollNumberAsc(id);for(RoundParticipant p:ps){RoundResult result=results.findByParticipantId(p.getId()).orElseThrow(()->DomainException.unprocessable("ROUND_RESULTS_INCOMPLETE","Every participant must have a result"));result.setPublished(true);JobApplication a=p.getApplication();ApplicationStatus next=result.getStatus()==RoundResultStatus.QUALIFIED?(a.getStatus()==ApplicationStatus.ELIGIBLE?ApplicationStatus.SHORTLISTED:ApplicationStatus.IN_PROCESS):ApplicationStatus.NOT_SELECTED;if(a.getStatus()!=next){ApplicationStatus from=a.getStatus();a.setStatus(next);ApplicationStatusHistory h=new ApplicationStatusHistory();h.setApplication(a);h.setFromStatus(from);h.setToStatus(next);h.setChangedBy(current.getCurrentUser());h.setReason("Published result for "+round.getName());history.save(h);}notifications.notify(a.getStudent().getUser(),"Round results published",round.getName()+": "+result.getStatus(),"ROUND_RESULT","/student/applications/"+a.getId());}round.setResultsPublished(true);audit.record("ROUND_RESULTS_PUBLISHED","SelectionRound",id,Map.of("participants",ps.size()));return dto(round);}
 private void apply(SelectionRound x,Upsert r){if(!r.endsAt().isAfter(r.startsAt()))throw DomainException.unprocessable("INVALID_ROUND_DATES","Round end must be after start");x.setName(r.name().trim());x.setRoundType(r.roundType().trim());x.setRoundOrder(r.roundOrder());x.setStartsAt(r.startsAt());x.setEndsAt(r.endsAt());x.setLocation(r.location());}
 private CampusDrive drive(Long id){return drives.findByIdAndInstitutionId(id,current.principal().institutionId()).orElseThrow(()->DomainException.notFound("Drive not found"));}private SelectionRound round(Long d,Long id){return rounds.findByIdAndDriveIdAndDriveInstitutionId(id,d,current.principal().institutionId()).orElseThrow(()->DomainException.notFound("Round not found"));}private RoundDto dto(SelectionRound r){return new RoundDto(r.getId(),r.getDrive().getId(),r.getName(),r.getRoundType(),r.getRoundOrder(),r.getStartsAt(),r.getEndsAt(),r.getLocation(),r.isResultsPublished(),r.getVersion());}private ParticipantDto participantDto(RoundParticipant p){RoundResult r=results.findByParticipantId(p.getId()).orElse(null);Student s=p.getApplication().getStudent();return new ParticipantDto(p.getId(),p.getApplication().getId(),s.getId(),s.getRollNumber(),(Objects.toString(s.getFirstName(),"")+" "+Objects.toString(s.getLastName(),"")).trim(),p.getAttendanceStatus(),r==null?RoundResultStatus.PENDING:r.getStatus(),r==null?null:r.getScore());}
}
