package com.keepcalm.placementportal.repository.drive;
import com.keepcalm.placementportal.repository.audit.*;
import com.keepcalm.placementportal.repository.communication.*;
import com.keepcalm.placementportal.repository.offer.*;
import com.keepcalm.placementportal.repository.selection.*;
import com.keepcalm.placementportal.repository.application.*;
import com.keepcalm.placementportal.repository.drive.*;
import com.keepcalm.placementportal.repository.company.*;
import com.keepcalm.placementportal.repository.profile.*;
import com.keepcalm.placementportal.repository.student.*;
import com.keepcalm.placementportal.repository.auth.*;
import com.keepcalm.placementportal.service.storage.*;
import com.keepcalm.placementportal.service.audit.*;
import com.keepcalm.placementportal.service.event.*;
import com.keepcalm.placementportal.service.analytics.*;
import com.keepcalm.placementportal.service.communication.*;
import com.keepcalm.placementportal.service.offer.*;
import com.keepcalm.placementportal.service.selection.*;
import com.keepcalm.placementportal.service.application.*;
import com.keepcalm.placementportal.service.drive.*;
import com.keepcalm.placementportal.service.company.*;
import com.keepcalm.placementportal.service.student.*;
import com.keepcalm.placementportal.service.profile.*;
import com.keepcalm.placementportal.service.auth.*;
import com.keepcalm.placementportal.entity.audit.*;
import com.keepcalm.placementportal.entity.communication.*;
import com.keepcalm.placementportal.entity.offer.*;
import com.keepcalm.placementportal.entity.selection.*;
import com.keepcalm.placementportal.entity.application.*;
import com.keepcalm.placementportal.entity.drive.*;
import com.keepcalm.placementportal.entity.company.*;
import com.keepcalm.placementportal.entity.profile.*;
import com.keepcalm.placementportal.entity.student.*;
import com.keepcalm.placementportal.entity.auth.*;
import com.keepcalm.placementportal.controller.event.*;
import com.keepcalm.placementportal.controller.analytics.*;
import com.keepcalm.placementportal.controller.communication.*;
import com.keepcalm.placementportal.controller.offer.*;
import com.keepcalm.placementportal.controller.selection.*;
import com.keepcalm.placementportal.controller.application.*;
import com.keepcalm.placementportal.controller.drive.*;
import com.keepcalm.placementportal.controller.company.*;
import com.keepcalm.placementportal.controller.student.*;
import com.keepcalm.placementportal.controller.profile.*;
import com.keepcalm.placementportal.controller.auth.*;
import com.keepcalm.placementportal.entity.drive.CampusDrive;
import com.keepcalm.placementportal.enums.DriveStatus;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.repository.*;
import org.springframework.data.repository.query.Param;
import java.util.*;
public interface CampusDriveRepository extends JpaRepository<CampusDrive,Long>{
 @Query("select d from CampusDrive d where d.institution.id=:iid and d.archived=false and d.status in :statuses and (:companyId is null or d.company.id=:companyId) and (:query is null or lower(d.title) like lower(concat('%',:query,'%')) or lower(d.company.name) like lower(concat('%',:query,'%')))")
 Page<CampusDrive> discover(@Param("iid")Long iid,@Param("statuses")Collection<DriveStatus>statuses,@Param("companyId")Long companyId,@Param("query")String query,Pageable pageable);
 Optional<CampusDrive> findByIdAndInstitutionId(Long id,Long institutionId);
 @Query("select d from CampusDrive d where d.institution.id=:iid and (:status is null or d.status=:status) and (:companyId is null or d.company.id=:companyId) and (:query is null or lower(d.title) like lower(concat('%',:query,'%')))")
 Page<CampusDrive> adminSearch(@Param("iid")Long iid,@Param("status")DriveStatus status,@Param("companyId")Long companyId,@Param("query")String query,Pageable pageable);
}
