package com.keepcalm.placementportal.repository.application;
import com.keepcalm.placementportal.repository.audit.*;
import com.keepcalm.placementportal.repository.communication.*;
import com.keepcalm.placementportal.repository.offer.*;
import com.keepcalm.placementportal.repository.selection.*;
import com.keepcalm.placementportal.repository.application.*;
import com.keepcalm.placementportal.repository.drive.*;
import com.keepcalm.placementportal.repository.company.*;
import com.keepcalm.placementportal.repository.profile.*;
import com.keepcalm.placementportal.repository.student.*;
import com.keepcalm.placementportal.repository.auth.*;
import com.keepcalm.placementportal.service.storage.*;
import com.keepcalm.placementportal.service.audit.*;
import com.keepcalm.placementportal.service.event.*;
import com.keepcalm.placementportal.service.analytics.*;
import com.keepcalm.placementportal.service.communication.*;
import com.keepcalm.placementportal.service.offer.*;
import com.keepcalm.placementportal.service.selection.*;
import com.keepcalm.placementportal.service.application.*;
import com.keepcalm.placementportal.service.drive.*;
import com.keepcalm.placementportal.service.company.*;
import com.keepcalm.placementportal.service.student.*;
import com.keepcalm.placementportal.service.profile.*;
import com.keepcalm.placementportal.service.auth.*;
import com.keepcalm.placementportal.entity.audit.*;
import com.keepcalm.placementportal.entity.communication.*;
import com.keepcalm.placementportal.entity.offer.*;
import com.keepcalm.placementportal.entity.selection.*;
import com.keepcalm.placementportal.entity.application.*;
import com.keepcalm.placementportal.entity.drive.*;
import com.keepcalm.placementportal.entity.company.*;
import com.keepcalm.placementportal.entity.profile.*;
import com.keepcalm.placementportal.entity.student.*;
import com.keepcalm.placementportal.entity.auth.*;
import com.keepcalm.placementportal.controller.event.*;
import com.keepcalm.placementportal.controller.analytics.*;
import com.keepcalm.placementportal.controller.communication.*;
import com.keepcalm.placementportal.controller.offer.*;
import com.keepcalm.placementportal.controller.selection.*;
import com.keepcalm.placementportal.controller.application.*;
import com.keepcalm.placementportal.controller.drive.*;
import com.keepcalm.placementportal.controller.company.*;
import com.keepcalm.placementportal.controller.student.*;
import com.keepcalm.placementportal.controller.profile.*;
import com.keepcalm.placementportal.controller.auth.*;
import com.keepcalm.placementportal.entity.application.JobApplication;
import com.keepcalm.placementportal.enums.ApplicationStatus;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.repository.*;
import org.springframework.data.repository.query.Param;
import java.util.*;
public interface JobApplicationRepository extends JpaRepository<JobApplication,Long>{
 boolean existsByDriveRoleIdAndStudentId(Long roleId,Long studentId);
 Optional<JobApplication> findByStudentIdAndIdempotencyKey(Long studentId,String key);
 Optional<JobApplication> findByIdAndStudentId(Long id,Long studentId);
 Optional<JobApplication> findByIdAndInstitutionId(Long id,Long institutionId);
 @Query("select a from JobApplication a where a.student.id=:studentId and (:status is null or a.status=:status) and (:driveId is null or a.driveRole.drive.id=:driveId) and (:roleId is null or a.driveRole.id=:roleId)")
 Page<JobApplication> studentApplications(@Param("studentId")Long studentId,@Param("status")ApplicationStatus status,@Param("driveId")Long driveId,@Param("roleId")Long roleId,Pageable pageable);
 @Query("select a from JobApplication a where a.institution.id=:iid and (:status is null or a.status=:status) and (:driveId is null or a.driveRole.drive.id=:driveId) and (:roleId is null or a.driveRole.id=:roleId) and (:query is null or lower(a.student.firstName) like lower(concat('%',:query,'%')) or lower(a.student.rollNumber) like lower(concat('%',:query,'%')))")
 Page<JobApplication> adminSearch(@Param("iid")Long iid,@Param("status")ApplicationStatus status,@Param("driveId")Long driveId,@Param("roleId")Long roleId,@Param("query")String query,Pageable pageable);
 List<JobApplication> findByDriveRoleDriveIdAndInstitutionId(Long driveId,Long institutionId);
 List<JobApplication> findByStudentIdOrderByAppliedAtDesc(Long studentId);
}
